# This workflow will do a clean install of node dependencies, build the source code, run tests and lint
name: build
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@koneksahealth'
      - name: Install Dependencies & Build
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_KONEKSA_DEPLOY_PAT_READ_ONLY}}
          GITHUB_TOKEN: ${{secrets.GH_KONEKSA_DEPLOY_PAT_READ_ONLY}}
      - name: Linter
        run: npm run lint
      - name: Tests
        run: npm test
