name: release
on:
  push:
    branches:
      - master
      - candidate-*
jobs:
  publish-gpr:
    runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
          run: npm ci
          run: npm run lint
          run: npm test
          run: npm semantic-release
