# This workflow will run tests using node and then publish a package to GitHub Packages when a code is merged to certain branches.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: release
on:
  push:
    branches:
      - master
      - candidate-*
jobs:
  publish-gpr:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@koneksahealth'
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_KONEKSA_DEPLOY_PAT_READ_ONLY}}
          GITHUB_TOKEN: ${{secrets.GH_KONEKSA_DEPLOY_PAT_READ_ONLY}}
      - name: Linter
        run: npm run lint
      - name: Tests
        run: npm test
      - name: Release and Publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
